# Generated by Django 4.0.1 on 2022-06-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_actuator_previous_value_sensor_previous_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='previous_value',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='value',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
