# Generated by Django 4.0.1 on 2022-08-25 04:57

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_sensor_previous_value_alter_sensor_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='set_time',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='set'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='set_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='actuator',
            name='set_value',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='previous_value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
