# Generated by Django 4.0.1 on 2022-09-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_deleted_at'),
        ('device', '0007_alter_actuator_previous_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
    ]
