# Generated by Django 4.0.1 on 2022-12-25 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_remove_user_otp_code'),
        ('device', '0010_alter_actuator_previous_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
    ]
