# Generated by Django 4.0.1 on 2023-01-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_alter_actuator_part_number_alter_sensor_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='title',
            field=models.CharField(default='', max_length=32),
        ),
    ]
