# Generated by Django 4.0.1 on 2023-01-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_organization_notification_interval'),
        ('device', '0015_alter_actuator_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actuator',
            unique_together={('organization', 'title')},
        ),
    ]
