# Generated by Django 4.0.1 on 2023-01-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0016_alter_actuator_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
