# Generated by Django 4.0.1 on 2023-02-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0017_type_max_type_min'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('name', 'id')},
        ),
    ]
