# Generated by Django 4.0.1 on 2023-02-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_alter_type_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
    ]
