# Generated by Django 4.0.1 on 2023-02-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0019_alter_type_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
