# Generated by Django 4.0.1 on 2022-06-16 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='notification',
        ),
        migrations.AddField(
            model_name='organizationnotification',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
    ]
