# Generated by Django 4.0.1 on 2022-06-30 05:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loggedinuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 5, 30, 46, 499628, tzinfo=utc)),
        ),
    ]
