# Generated by Django 4.0.1 on 2022-06-30 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_loggedinuser_is_online_loggedinuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedinuser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
