# Generated by Django 4.0.1 on 2022-06-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_loggedinuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='channel_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
