# Generated by Django 4.0.1 on 2022-08-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_loggedinuser_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='telegram',
            field=models.BooleanField(default=False),
        ),
    ]
