# Generated by Django 4.0.1 on 2022-08-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_organization_email_organization_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='automation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.AddField(
            model_name='organization',
            name='automation',
            field=models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic'), ('smart', 'smart')], max_length=16, null=True),
        ),
    ]
