# Generated by Django 4.0.1 on 2022-10-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_last_name_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cash',
            field=models.IntegerField(default=100000),
        ),
    ]
