# Generated by Django 4.0.1 on 2022-10-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_organization_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sms_price',
            field=models.IntegerField(default=510),
        ),
    ]
