# Generated by Django 4.0.1 on 2022-11-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_organization_sms_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='algorithm',
            field=models.CharField(choices=[('FORWARD', 'FORWARD'), ('BACKWARD', 'BACKWARD')], max_length=8, null=True),
        ),
    ]
