# Generated by Django 4.0.1 on 2022-11-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
