# Generated by Django 4.0.1 on 2022-12-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_user_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_code',
        ),
    ]
