# Generated by Django 4.0.1 on 2023-01-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notification_interval',
            field=models.IntegerField(default=1800),
        ),
    ]
