# Generated by Django 4.0.1 on 2023-03-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_alter_user_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('organization', 'phone')},
        ),
    ]
