# Generated by Django 4.0.1 on 2024-02-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remain_account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
