# Generated by Django 4.0.1 on 2022-10-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplefunction',
            name='data',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='status',
        ),
    ]
