# Generated by Django 4.0.1 on 2022-10-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_simplefunction_data_remove_tile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='status',
            field=models.JSONField(null=True),
        ),
    ]
