# Generated by Django 4.0.1 on 2022-10-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_tile_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
