# Generated by Django 4.0.1 on 2023-02-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_tab_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='title',
            field=models.CharField(error_messages={'max_length': 'طول فیلد حداکثر 24 کارکتر باشد'}, max_length=24),
        ),
    ]
