# Generated by Django 4.0.1 on 2023-11-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_tile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='precision',
            field=models.CharField(choices=[('1', '1'), ('0.1', '0.1'), ('0.01', '0.01')], max_length=8),
        ),
    ]
