# Generated by Django 4.0.1 on 2022-06-07 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('automatic', 'automatic'), ('manual', 'manual')], max_length=16)),
                ('trigger', models.CharField(blank=True, choices=[('OFF', 'OFF'), ('ON', 'ON'), ('SWITCH', 'SWITCH')], max_length=8, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'automation_notification',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SmartTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, unique=True)),
                ('path', models.FilePathField(blank=True, null=True, path='/var/www/Angizeh_2/Smart_Plans/', unique=True)),
                ('active', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
            options={
                'db_table': 'smart_tile',
            },
        ),
        migrations.CreateModel(
            name='ManualTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuator_value', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=24)),
                ('order', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
                ('lock', models.BooleanField(default=False)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.actuator')),
                ('alarm', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.automationnotification')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
            options={
                'db_table': 'manual_tile',
                'ordering': ('field', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CONTINUES', 'CONTINUES'), ('BINARY', 'BINARY'), ('SCHEDULE', 'SCHEDULE')], default='CONTINUES', max_length=16)),
                ('operator', models.CharField(choices=[('LT', 'Lower Than'), ('HT', 'Higher Than'), ('EQ', 'Equal To'), ('ON', 'ON'), ('OFF', 'OFF'), ('SWITCH', 'SWITCH'), ('ONCE', 'ONCE'), ('HO', 'Hourly'), ('DA', 'Daily'), ('WE', 'Weekly'), ('MO', 'Monthly'), ('SE', 'Seasonally'), ('YE', 'Yearly')], max_length=8)),
                ('set_time', models.DateTimeField(blank=True, null=True)),
                ('set_point', models.FloatField(blank=True, null=True)),
                ('set_state', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF'), ('SWITCH', 'SWITCH')], max_length=8, null=True)),
                ('status', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.sensor')),
            ],
            options={
                'db_table': 'automation_condition',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AutomaticTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regulation', 'regulation'), ('schedule', 'schedule')], max_length=16)),
                ('title', models.CharField(max_length=24)),
                ('delay_status', models.BooleanField(default=False)),
                ('delay', models.CharField(blank=True, choices=[('1m', '1m'), ('5m', '5m'), ('30m', '30m'), ('1h', '1h')], max_length=3, null=True)),
                ('output', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('SWITCH', 'SWITCH')], default='ON', max_length=8)),
                ('counter', models.IntegerField(blank=True, default=0, null=True)),
                ('monitor', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='counter')),
                ('order', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
                ('lock', models.BooleanField(default=False)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.actuator')),
                ('alarm', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.automationnotification')),
                ('condition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.condition')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
            options={
                'db_table': 'automatic_tile',
                'ordering': ('field', 'order'),
            },
        ),
    ]
