# Generated by Django 4.0.1 on 2022-07-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatictile',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='automatictile',
            name='monitor',
        ),
    ]
