# Generated by Django 4.0.1 on 2022-07-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_automatictile_alarm_alter_manualtile_alarm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatictile',
            name='alarm',
        ),
        migrations.RemoveField(
            model_name='manualtile',
            name='alarm',
        ),
    ]
