# Generated by Django 4.0.1 on 2022-07-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_alter_notificationmanager_action_object_content_type'),
        ('automation', '0006_remove_manualtile_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtile',
            name='alarm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationmanager'),
        ),
    ]
