# Generated by Django 4.0.1 on 2022-08-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_manualtile_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatictile',
            name='condition',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
