# Generated by Django 4.0.1 on 2022-08-04 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('automation', '0009_schedulecondition_continuescondition_binarycondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatictile',
            name='condition_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('continuescondition', 'binarycondition', 'schedulecondition')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='automatictile',
            name='condition_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
