# Generated by Django 4.0.1 on 2022-08-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_automatictile_condition_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binarycondition',
            name='if_content_type',
        ),
        migrations.RemoveField(
            model_name='continuescondition',
            name='if_object',
        ),
        migrations.DeleteModel(
            name='ScheduleCondition',
        ),
        migrations.RemoveField(
            model_name='automatictile',
            name='condition_content_type',
        ),
        migrations.RemoveField(
            model_name='automatictile',
            name='condition_object_id',
        ),
        migrations.DeleteModel(
            name='BinaryCondition',
        ),
        migrations.DeleteModel(
            name='ContinuesCondition',
        ),
    ]
