# Generated by Django 4.0.1 on 2022-08-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_automatictile_condition_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatictile',
            name='alarm',
        ),
    ]
