# Generated by Django 4.0.1 on 2022-08-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_alter_notificationmanager_condition'),
        ('automation', '0013_remove_automatictile_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatictile',
            name='alarm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationmanager'),
        ),
    ]
