# Generated by Django 4.0.1 on 2022-08-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_automatictile_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatictile',
            name='alarm',
        ),
    ]
