# Generated by Django 4.0.1 on 2022-08-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0015_remove_automatictile_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualtile',
            name='alarm',
        ),
    ]
