# Generated by Django 4.0.1 on 2022-08-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_remove_manualtile_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualtile',
            name='actuator_value',
        ),
    ]
