# Generated by Django 4.0.1 on 2022-08-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_sensor_previous_value_alter_sensor_value'),
        ('automation', '0017_remove_manualtile_actuator_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatictile',
            name='actuator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.actuator'),
        ),
    ]
