# Generated by Django 4.0.1 on 2022-08-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_alter_automatictile_condition_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatictile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='manualtile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='smarttile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
