# Generated by Django 4.0.1 on 2022-09-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0021_alter_automatictile_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatictile',
            name='status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('STARTED', 'STARTED'), ('RETRYING', 'RETRYING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='WAITING', max_length=8),
        ),
    ]
