# Generated by Django 4.0.1 on 2022-09-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0023_alter_automatictile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtile',
            name='status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('STARTED', 'STARTED'), ('RETRYING', 'RETRYING'), ('SUCCEED', 'SUCCEED'), ('FAILED', 'FAILED')], default='WAITING', max_length=8),
        ),
    ]
