# Generated by Django 4.0.1 on 2022-09-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_actuator_previous_value_and_more'),
        ('automation', '0024_manualtile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtile',
            name='actuator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.actuator', unique=True),
        ),
    ]
