# Generated by Django 4.0.1 on 2022-09-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0025_alter_manualtile_actuator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatictile',
            name='title',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='manualtile',
            name='title',
            field=models.CharField(default='', max_length=24, unique=True),
        ),
    ]
