# Generated by Django 4.0.1 on 2022-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0028_alter_manualtile_actuator'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manualtile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('title', 'actuator'), name='unique_manual_name'),
        ),
    ]
