# Generated by Django 4.0.1 on 2022-09-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0029_manualtile_unique_manual_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='manualtile',
            name='unique_manual_name',
        ),
        migrations.AddConstraint(
            model_name='manualtile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('title', 'actuator_id'), name='unique_manual_name'),
        ),
    ]
