# Generated by Django 4.0.1 on 2022-11-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0035_automatictile_actuator_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatictile',
            name='output',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=8),
        ),
    ]
