# Generated by Django 4.0.1 on 2023-01-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0036_alter_automatictile_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtile',
            name='title',
            field=models.CharField(default='', max_length=24),
        ),
    ]
