# Generated by Django 4.0.1 on 2022-08-04 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0003_alter_sensor_previous_value_alter_sensor_value'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('ONCE', 'ONCE'), ('HO', 'Hourly'), ('DA', 'Daily'), ('WE', 'Weekly'), ('MO', 'Monthly'), ('SE', 'Seasonally'), ('YE', 'Yearly')], max_length=6)),
                ('set_time', models.DateTimeField(blank=True, null=True)),
                ('last_time_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContinuesCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('LT', 'Lower Than'), ('HT', 'Higher Than'), ('EQ', 'Equal To')], max_length=2)),
                ('if_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='BinaryCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('SWITCH', 'SWITCH')], max_length=6)),
                ('if_object_id', models.PositiveIntegerField()),
                ('if_content_type', models.ForeignKey(limit_choices_to={'model__in': ('sensor', 'actuator')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
