# Generated by Django 4.0.1 on 2022-08-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('device', '0003_alter_sensor_previous_value_alter_sensor_value'),
        ('condition', '0002_continuescondition_set_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BinaryCondition',
            new_name='Binary',
        ),
        migrations.RenameModel(
            old_name='ContinuesCondition',
            new_name='Continues',
        ),
        migrations.RenameModel(
            old_name='ScheduleCondition',
            new_name='Schedule',
        ),
    ]
