# Generated by Django 4.0.1 on 2022-08-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_sensor_previous_value_alter_sensor_value'),
        ('condition', '0003_rename_binarycondition_binary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continues',
            old_name='if_object',
            new_name='sensor',
        ),
        migrations.RemoveField(
            model_name='binary',
            name='if_content_type',
        ),
        migrations.RemoveField(
            model_name='binary',
            name='if_object_id',
        ),
        migrations.AddField(
            model_name='binary',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.sensor'),
        ),
    ]
