# Generated by Django 4.0.1 on 2022-08-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0004_rename_if_object_continues_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='operator',
            field=models.CharField(choices=[('ONCE', 'ONCE'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('SEASONALLY', 'Seasonally'), ('YEARLY', 'Yearly')], max_length=16),
        ),
    ]
