# Generated by Django 4.0.1 on 2022-08-11 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_sensor_previous_value_alter_sensor_value'),
        ('condition', '0005_alter_schedule_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.sensor'),
        ),
        migrations.AlterField(
            model_name='continues',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.sensor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='last_time_run',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='set_time',
            field=models.DateTimeField(),
        ),
    ]
