# Generated by Django 4.0.1 on 2022-08-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0006_alter_binary_sensor_alter_continues_sensor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='last_time_run',
            new_name='update_time',
        ),
    ]
