# Generated by Django 4.0.1 on 2022-08-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0007_rename_last_time_run_schedule_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
