# Generated by Django 4.0.1 on 2023-01-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0008_schedule_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='update_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
