# Generated by Django 4.0.1 on 2023-01-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0009_remove_schedule_update_time_schedule_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='binary',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='continues',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
