# Generated by Django 4.0.1 on 2022-07-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_notificationmanager_action_object_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmanager',
            name='condition',
            field=models.CharField(blank=True, choices=[('lt', 'lt'), ('ht', 'ht'), ('eq', 'eq'), ('on', 'on'), ('off', 'off'), ('switch', 'switch')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='notificationmanager',
            name='set_point',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
