# Generated by Django 4.0.1 on 2022-07-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0012_alter_notificationmanager_action_object_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmanager',
            name='action_object_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
