# Generated by Django 4.0.1 on 2022-07-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0016_alter_notificationmanager_action_object_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmanager',
            name='action_object_content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('sensor', 'actuator', 'manualtile', 'automatictile')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
