# Generated by Django 4.0.1 on 2022-07-31 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0017_alter_notificationmanager_action_object_content_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationmanager',
            unique_together={('title', 'action_object_content_type', 'action_object_id')},
        ),
    ]
