# Generated by Django 4.0.1 on 2022-07-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_alter_notificationmanager_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmanager',
            name='condition',
            field=models.CharField(blank=True, choices=[('lt', 'lt'), ('ht', 'ht'), ('eq', 'eq'), ('on', 'on'), ('off', 'off'), ('switch', 'switch'), ('connect', 'connect'), ('disconnect', 'disconnect')], max_length=10, null=True),
        ),
    ]
