# Generated by Django 4.0.1 on 2022-07-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_notificationmanager_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmanager',
            name='condition',
            field=models.CharField(blank=True, choices=[('LT', 'LT'), ('HT', 'HT'), ('EQ', 'EQ'), ('ON', 'ON'), ('OFF', 'OFF'), ('SWITCH', 'SWITCH'), ('CONNECT', 'CONNECT'), ('DISCONNECT', 'DISCONNECT')], max_length=10, null=True),
        ),
    ]
