# Generated by Django 4.0.1 on 2022-09-10 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_notificationmanager_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmanager',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 15, 1, 50, 999114, tzinfo=utc)),
        ),
    ]
