# Generated by Django 4.0.1 on 2023-01-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0025_alter_notificationmanager_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmanager',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
